package com.mqfdy.code.springboot.core.validators;

import org.eclipse.core.runtime.IStatus;

// TODO: Auto-generated Javadoc
/**
 * A value representing the result of a wizard page validation. 
 * 
 * @author lenovo
 */
public class ValidationResult {
	
	/** The msg. */
	public final String msg;
	
	/** The status. */
	public int status; 
	
	private ValidationResult(int status, String msg) {
		this.msg = msg;
		this.status = status;
	}
	
	/**
	 * Checks if is ok.
	 *
	 * @author mqfdy
	 * @return true, if is ok
	 * @Date 2018-09-03 09:00
	 */
	public boolean isOk() {
		return status == IStatus.OK;
	}
	
	/** The Constant OK. */
	public static final ValidationResult OK = new ValidationResult(IStatus.OK, null);
	
	/**
	 * Error.
	 *
	 * @author mqfdy
	 * @param msg
	 *            the msg
	 * @return the validation result
	 * @Date 2018-09-03 09:00
	 */
	public static ValidationResult error(String msg) {
		return new ValidationResult(IStatus.ERROR, msg);
	}
	
	/**
	 * Warning.
	 *
	 * @author mqfdy
	 * @param msg
	 *            the msg
	 * @return the validation result
	 * @Date 2018-09-03 09:00
	 */
	public static ValidationResult warning(String msg) {
		return new ValidationResult(IStatus.WARNING, msg);
	}
	
	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		//generated by eclipse
		final int prime = 31;
		int result = 1;
		result = prime * result + ((msg == null) ? 0 : msg.hashCode());
		result = prime * result + status;
		return result;
	}
	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj) {
		//generated by eclipse
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		ValidationResult other = (ValidationResult) obj;
		if (msg == null) {
			if (other.msg != null)
				return false;
		} else if (!msg.equals(other.msg))
			return false;
		if (status != other.status)
			return false;
		return true;
	}
	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "ValidationResult [msg=" + msg + ", status=" + status(status) + "]";
	}
	
	private static String status(int s) {
		switch (s) {
		case IStatus.ERROR:
			return "ERROR";
		case IStatus.WARNING:
			return "WARNING";	
		default:
			return ""+s;
		}
	}
	
	
}
