/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 4.1 */
package org.apache.velocity.runtime.parser;

// TODO: Auto-generated Javadoc
/**
 * The Interface ParserTreeConstants.
 *
 * @author mqfdy
 */
public interface ParserTreeConstants
{
  
  /** The jjtprocess. */
  public int JJTPROCESS = 0;
  
  /** The jjtvoid. */
  public int JJTVOID = 1;
  
  /** The jjtescapeddirective. */
  public int JJTESCAPEDDIRECTIVE = 2;
  
  /** The jjtescape. */
  public int JJTESCAPE = 3;
  
  /** The jjtcomment. */
  public int JJTCOMMENT = 4;
  
  /** The jjttextblock. */
  public int JJTTEXTBLOCK = 5;
  
  /** The jjtfloatingpointliteral. */
  public int JJTFLOATINGPOINTLITERAL = 6;
  
  /** The jjtintegerliteral. */
  public int JJTINTEGERLITERAL = 7;
  
  /** The jjtstringliteral. */
  public int JJTSTRINGLITERAL = 8;
  
  /** The jjtidentifier. */
  public int JJTIDENTIFIER = 9;
  
  /** The jjtword. */
  public int JJTWORD = 10;
  
  /** The jjtdirective. */
  public int JJTDIRECTIVE = 11;
  
  /** The jjtblock. */
  public int JJTBLOCK = 12;
  
  /** The jjtmap. */
  public int JJTMAP = 13;
  
  /** The jjtobjectarray. */
  public int JJTOBJECTARRAY = 14;
  
  /** The jjtintegerrange. */
  public int JJTINTEGERRANGE = 15;
  
  /** The jjtmethod. */
  public int JJTMETHOD = 16;
  
  /** The jjtindex. */
  public int JJTINDEX = 17;
  
  /** The jjtreference. */
  public int JJTREFERENCE = 18;
  
  /** The jjttrue. */
  public int JJTTRUE = 19;
  
  /** The jjtfalse. */
  public int JJTFALSE = 20;
  
  /** The jjttext. */
  public int JJTTEXT = 21;
  
  /** The jjtifstatement. */
  public int JJTIFSTATEMENT = 22;
  
  /** The jjtelsestatement. */
  public int JJTELSESTATEMENT = 23;
  
  /** The jjtelseifstatement. */
  public int JJTELSEIFSTATEMENT = 24;
  
  /** The jjtsetdirective. */
  public int JJTSETDIRECTIVE = 25;
  
  /** The jjtexpression. */
  public int JJTEXPRESSION = 26;
  
  /** The jjtassignment. */
  public int JJTASSIGNMENT = 27;
  
  /** The jjtornode. */
  public int JJTORNODE = 28;
  
  /** The jjtandnode. */
  public int JJTANDNODE = 29;
  
  /** The jjteqnode. */
  public int JJTEQNODE = 30;
  
  /** The jjtnenode. */
  public int JJTNENODE = 31;
  
  /** The jjtltnode. */
  public int JJTLTNODE = 32;
  
  /** The jjtgtnode. */
  public int JJTGTNODE = 33;
  
  /** The jjtlenode. */
  public int JJTLENODE = 34;
  
  /** The jjtgenode. */
  public int JJTGENODE = 35;
  
  /** The jjtaddnode. */
  public int JJTADDNODE = 36;
  
  /** The jjtsubtractnode. */
  public int JJTSUBTRACTNODE = 37;
  
  /** The jjtmulnode. */
  public int JJTMULNODE = 38;
  
  /** The jjtdivnode. */
  public int JJTDIVNODE = 39;
  
  /** The jjtmodnode. */
  public int JJTMODNODE = 40;
  
  /** The jjtnotnode. */
  public int JJTNOTNODE = 41;


  /** The jjt node name. */
  public String[] jjtNodeName = {
    "process",
    "void",
    "EscapedDirective",
    "Escape",
    "Comment",
    "Textblock",
    "FloatingPointLiteral",
    "IntegerLiteral",
    "StringLiteral",
    "Identifier",
    "Word",
    "Directive",
    "Block",
    "Map",
    "ObjectArray",
    "IntegerRange",
    "Method",
    "Index",
    "Reference",
    "True",
    "False",
    "Text",
    "IfStatement",
    "ElseStatement",
    "ElseIfStatement",
    "SetDirective",
    "Expression",
    "Assignment",
    "OrNode",
    "AndNode",
    "EQNode",
    "NENode",
    "LTNode",
    "GTNode",
    "LENode",
    "GENode",
    "AddNode",
    "SubtractNode",
    "MulNode",
    "DivNode",
    "ModNode",
    "NotNode",
  };
}
/* JavaCC - OriginalChecksum=711f18baf1c477a8c95d1c28eaa4b636 (do not edit this line) */
