package com.mqfdy.code.designer.views.properties.sources;

/**
 * 常量
 * 
 * @author mqfdy
 * 
 */
public interface IBusinessModelPropertyNames {
	String PROPERTY_COMMON_ID = "id";
	String PROPERTY_COMMON_NAME = "名称";
	String PROPERTY_COMMON_NAMESPACE = "命名空间";
	String PROPERTY_COMMON_DISPLAYNAME = "显示名称";
	String PROPERTY_COMMON_REMARK = "备注";
	String PROPERTY_COMMON_OBJECTTYPE = "类型";
	String PROPERTY_COMMON_STEREOTYPETYPE = "构造类型";
	String PROPERTY_BUSINESSCLASS_TABLENAME = "数据库表名";
	String PROPERTY_BUSINESSCLASS_ISABSTRACT = "IsAbstract";
	String PROPERTY_BUSINESSCLASS_ISCRIGHT = "ISCRight";

	String PROPERTY_BUSINESSCLASS_properties = "properties";
	String PROPERTY_BUSINESSCLASS_groups = "groups";
	String PROPERTY_BUSINESSCLASS_operations = "operations";
	String PROPERTY_BUSINESSCLASS_statuses = "statuses";
	String PROPERTY_BUSINESSCLASS_permissions = "permissions";
	String PROPERTY_BUSINESSCLASS_versionInfo = "versionInfo";
	// String PROPERTY_STEREOTYPE = "stereotype";
	// String PROPERTY_STEREOTYPE = "stereotype";
	// String PROPERTY_STEREOTYPE = "stereotype";
	// String PROPERTY_STEREOTYPE = "stereotype";
	// String PROPERTY_STEREOTYPE = "stereotype";
	// String PROPERTY_STEREOTYPE = "stereotype";
	String PROPERTY_ASSOCIATION_CLASSA = "实体A";// OBJECT TEXT+BUTTON
	String PROPERTY_ASSOCIATION_CLASSB = "实体B";// OBJECT TEXT+BUTTON
	String PROPERTY_ASSOCIATION_ASSOCIATIONTYPE = "关联类型";
	String PROPERTY_ASSOCIATION_NAVIGETETOCLASSB = "支持导航到实体B";// boolean
	String PROPERTY_ASSOCIATION_NAVIGETETOCLASSA = "支持导航到实体A";// boolean
	String PROPERTY_ASSOCIATION_CASCADEDELETECLASSB = "级联删除实体B";// boolean
	String PROPERTY_ASSOCIATION_CASCADEDELETECLASSA = "级联删除实体A";// boolean
	String PROPERTY_ASSOCIATION_PERSISTENCEPLOY = "持久化策略";
	String PROPERTY_ASSOCIATION_MITABLENAME = "中间表名";
	String PROPERTY_ASSOCIATION_COLUMNOFCLASSA = "实体A数据库表关联字段";
	String PROPERTY_ASSOCIATION_COLUMNOFCLASSB = "实体B数据库表关联字段";
	String PROPERTY_ASSOCIATION_MAJOR_CLASSNAME = "主控端名称";

	String PROPERTY_INHERITANCE_PARENTCLASS = "父实体";// OBJECT TEXT+BUTTON
	String PROPERTY_INHERITANCE_CHILDCLASS = "子实体";// OBJECT TEXT+BUTTON
	String PROPERTY_INHERITANCE_PERSISTENCEPLOY = "持久化策略";
	String PROPERTY_INHERITANCE_PERSITENCEPLOYPARAMS = "persistencePloyParams";// OBJECT
																				// TEXT+BUTTON

	String PROPERTY_PKPROPERTY_PKNAME = "pkName";
	String PROPERTY_PKPROPERTY_PRIMARYKEYPLOY = "primaryKeyPloy";

	String PROPERTY_PROPERTY_GROUP = "属性分组";// OBJECT TEXT+BUTTON
	String PROPERTY_PROPERTY_DATATYPE = "数据类型";
	String PROPERTY_PROPERTY_DEFAULTVALUE = "缺省值";
	String PROPERTY_PROPERTY_VALIDATORS = "数据校验";
	String PROPERTY_PROPERTY_ORDERNUM = "orderNum";

	String PROPERTY_ENUMERARION_VALUES = "values";

	String PROPERTY_REFERENCEOBJECT_MODELID = "referenceModelId";
	String PROPERTY_REFERENCEOBJECT_OBJECTID = "referenceObjectId";
	String PROPERTY_REFERENCEOBJECT_MODELPATH = "referenceModePath";
	String PROPERTY_REFERENCEOBJECT_OBJECT = "referenceObject";

	String PROPERTY_PERSISTENCEPROPERTY_PROPERTYTYPE = "属性类型";
	String PROPERTY_PERSISTENCEPROPERTY_PROPERTYGROUP = "属性分组";
	String PROPERTY_PERSISTENCEPROPERTY_ISPERSITENCEPROPERTY = "是否持久化属性";
	String PROPERTY_PERSISTENCEPROPERTY_DEFAULTVALUE = "缺省值";
	String PROPERTY_PERSISTENCEPROPERTY_ISPRIMARYKEY = "是否主键";
	String PROPERTY_PERSISTENCEPROPERTY_ISNULLABLE = "可空";
	String PROPERTY_PERSISTENCEPROPERTY_ISINDEXEDCOLUMN = "索引列";
	String PROPERTY_PERSISTENCEPROPERTY_ISREADONLY = "只读";
	String PROPERTY_PERSISTENCEPROPERTY_ISUNIQUE = "值唯一";
	String PROPERTY_PERSISTENCEPROPERTY_PRIMARYKEYPLOY = "主键生成策略";
	String PROPERTY_PERSISTENCEPROPERTY_PLOYNAME = "主键名称";
	String PROPERTY_PERSISTENCEPROPERTY_DBCOLUMNNAME = "数据库字段名称";
	// String PROPERTY_PERSISTENCEPROPERTY_DBDATATYPE = "数据库字段类型";
	String PROPERTY_PERSISTENCEPROPERTY_DBDATALENGTH = "数据库字段长度";
	String PROPERTY_PERSISTENCEPROPERTY_PRECISION = "数据库字段精度";
	String PROPERTY_PERSISTENCEPROPERTY_VALIDATOR = "校验器列表";
	String PROPERTY_PERSISTENCEPROPERTY_PROPERTYEDITOR = "属性编辑器";

	String PROPERTY_OPERATION_RETURNDATATYPE = "返回数据类型";
	String PROPERTY_OPERATION_TRANSACTIONSUPPORT = "事务支持";
	String PROPERTY_OPERATION_EXCEPTIONMESSAGE = "异常提示信息";
	String PROPERTY_OPERATION_PARAMETERINFO = "参数信息";

	String PROPERTY_VERSION_VERSIONNUM = "版本号";
	String PROPERTY_VERSION_CREATER = "创建人";
	String PROPERTY_VERSION_CREATETIME = "创建时间";
	String PROPERTY_VERSION_UPDATER = "最后修改人";
	String PROPERTY_VERSION_UPDATETIME = "最后修改时间";

	String PROPERTY_ENUMELEMENT_KEY = "键";
	String PROPERTY_ENUMELEMENT_VALUE = "键值";

	String CATEGORY_VERSION = "版本信息";
	// 引用对象
	String REFERENCEOBJECT_REFERENCEMODELID = "引用模型编号";
	String REFERENCEOBJECT_REFERENCEOBJECTID = "引用对象编号";
	String REFERENCEOBJECT_REFERENCEMODEPATH = "引用模型路径";
	/**
	 * 是否 查询属性
	 */
	// private boolean isQueryProterty;

	String PROPERTY_ID = "id";
	String PROPERTY_NAME = "name";
	String CATEGORY_1 = "基本信息";
	String CATEGORY_ASSOCIATION = "Association";
	String CATEGORY_ASSOCIATIONA = "实体A";
	String CATEGORY_ASSOCIATIONB = "实体B";
	String CATEGORY_ASSOCIATION_PERSISTENCEPLOY = "持久化策略";
	String CATEGORY_PROPERTY_PERSISTENCEPLOY = "持久化策略";
	String CATEGORY_PKPROPERTY = "PKProperty";
	String CATEGORY_BUSINESSCLASS = "BusinessClass";
	String CATEGORY_ENUMERARION = "Enumeration";
	String CATEGORY_REFERENCEOBJECT = "ReferenceObject";
	String CATEGORY_PROPERTY = "Property";
	String CATEGORY_INHERITANCE = "Inheritance";
	String CATEGORY_Style = "Style";
	String XPOS_PROP = "xpos";
	String YPOS_PROP = "ypos";
	String HEIGHT_PROP = "height";
	String WIDTH_PROP = "width";
	String CATEGORY_BASE = "基本信息";
}
